import = ["~/.config/alacritty/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12
builtin_box_drawing = true 
offset = { y= 4 }
glyph_offset = { y= 2 }

[font.normal]
family = "ZedMono Nerd Font"

[window]
padding = { x = 3, y = 3 }
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
# opacity = 0.9
# blur = true 

# theme: rose-pine
[colors.primary]
foreground = "#e0def4"
background = "#232136"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#56526e"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#56526e"

[colors.search.matches]
foreground = "#908caa"
background = "#393552"

[colors.search.focused_match]
foreground = "#232136"
background = "#ea9a97"

[colors.hints.start]
foreground = "#908caa"
background = "#2a273f"

[colors.hints.end]
foreground = "#6e6a86"
background = "#2a273f"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#2a273f"

[colors.selection]
text = "#e0def4"
background = "#44415a"

[colors.normal]
black = "#393552"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"

# theme: Kanagawa

# [colors.primary]
# background= "#1f1f28"
# foreground= "#dcd7ba"
#
# [colors.selection]
# background= "#2d4f67"
# foreground= "#c8c093"
#
# [[colors.indexed_colors]]
# color = "#ffa066"
# index = 16
#
# [[colors.indexed_colors]]
# color = "#c8c093"
# index = 17
#
# # # Normal colors
# [colors.normal]
# black=   "#090618"
# red=     "#c34043"
# green=   "#76946a"
# yellow=  "#c0a36e"
# blue=    "#7e9cd8"
# magenta= "#957fb8"
# cyan=    "#6a9589"
# white=   "#c8c093"
#
# # # Bright colors
# [colors.bright]
# black=   "#727169"
# red=     "#e82424"
# green=   "#98bb6c"
# yellow=  "#e6c384"
# blue=    "#7fb4ca"
# magenta= "#938aa9"
# cyan=    "#7aa89f"
# white=   "#dcd7ba"
