[shell]
program = "wsl.exe"
args = ["--cd ~"]

[env]
TERM = "xterm-256color"

[font]
size = 12
builtin_box_drawing = true 
offset = { y= 4 }
glyph_offset = { y= 2 }

[font.normal]
family = "ZedMono Nerd Font"

[window]
padding = { x = 3, y = 3 }
# startup_mode = "Windowed"
# title = "Alacritty"
# dynamic_title = true 
# decorations_theme_variant = "None"
# decorations = "Full"
opacity = 0.9
# blur = true 

[colors.primary]
background= "#1f1f28"
foreground= "#dcd7ba"

[colors.selection]
background= "#2d4f67"
foreground= "#c8c093"

[[colors.indexed_colors]]
color = "#ffa066"
index = 16

[[colors.indexed_colors]]
color = "#c8c093"
index = 17

# # Normal colors
[colors.normal]
black=   "#090618"
red=     "#c34043"
green=   "#76946a"
yellow=  "#c0a36e"
blue=    "#7e9cd8"
magenta= "#957fb8"
cyan=    "#6a9589"
white=   "#c8c093"

# # Bright colors
[colors.bright]
black=   "#727169"
red=     "#e82424"
green=   "#98bb6c"
yellow=  "#e6c384"
blue=    "#7fb4ca"
magenta= "#938aa9"
cyan=    "#7aa89f"
white=   "#dcd7ba"
