format = """
$directory\
$git_branch\
$cmd_duration $jobs\
$character"""

[directory]
style = "blue"
read_only = " "
truncation_length = 1
truncation_symbol = '../'
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = '[::](blue) [$branch]($style)'
style = "red"

[cmd_duration]
format = ' [::](blue) [$duration]($style)'
style = "yellow"
