preload=~/Downloads/def-wallpapers/blue-bg.png

wallpaper=eDP-1,~/Downloads/def-wallpapers/blue-bg.png
wallpaper=HDMI-A-2,~/Downloads/def-wallpapers/blue-bg.png

splash = false

#fully disable ipc
ipc = off


