return {
  -- {
  --   'williamboman/mason.nvim',
  --   config = true,
  -- },
  -- {
  --   'williamboman/mason-lspconfig.nvim',
  --   config = function()
  --     local mason_lspconfig = require('mason-lspconfig')
  --
  --     mason_lspconfig.setup({
  --       ensure_installed = {
  --         'tsserver',
  --         'html',
  --         'cssls',
  --         'tailwindcss',
  --         'svelte',
  --         'lua_ls',
  --         'graphql',
  --         'emmet_ls',
  --         'prismals',
  --       },
  --       automatic_installation = true,
  --     })
  --   end,
  -- },
}
