set -g default-terminal "tmux-256color"
set -ga terminal-features ",*:usstyle"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Smulc=\E[4::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=red,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

## ------ KANAGAWA -------------
# Colores Kanagawa
set -g status-bg "#1f1f28"
set -g status-fg "#DCD7BA"

# Separadores y estilos
set -g window-status-separator "#[fg=#1F1F28,fg=#1F1F28]█"
set -g window-status-format " #W"
set -g window-status-format "#[bg=#1F1F28,fg=#2A2A37]#[bg=#2A2A37,fg=#DCD7BA]#W#[bg=#2A2A37,fg=#2A2A37]█#[bg=#7E9CD8,fg=#7E9CD8]█#[bg=#7E9CD8,fg=#1F1F28]#I#[fg=#7E9CD8,bg=#1F1F28]"
set -g window-status-current-format "#[bg=#1F1F28,fg=#2A2A37]#[bg=#2A2A37,fg=#DCD7BA]#W#[bg=#2A2A37,fg=#2A2A37]█#[fg=#FF9E3B,bg=#2A2A37]█#[bg=#FF9E3B,fg=#2A2A37]#I#[fg=#FF9E3B,bg=#1F1F28]"

# Status izquierdo y derecho

# set -g status-left " #[bg=#1F1F28,fg=#6A9589]#[fg=#1F1F28,bg=#6A9589] #[bg=#2A2A37,fg=#2A2A37]█#[bg=#2A2A37,fg=#DCD7BA]tmux#[bg=#1F1F28,fg=#2A2A37] "
 set -g status-left " "
set -g status-right "#[bg=#1F1F28,fg=#7E9CD8]#[bg=#7E9CD8,fg=#1F1F28] #[bg=#2A2A37,fg=#2A2A37]█#[bg=#2A2A37,fg=#DCD7BA]%H:%M#[fg=#2A2A37,bg=#1F1F28] "

run '~/.tmux/plugins/tpm/tpm'
